### ISSUE TITLE
Can't compile a bunch of messages programmatically

### ISSUE THREAD

**Issue by otbe** [SlexAxton/messageformat.js#103]
Hi,

we want to use your tool in a custom build flow programmatically. But something went wrong if we try to compile a bunch of messages. From your examples:

```javascript
var mf = new MessageFormat('en');
var messages = {
    simple: 'A simple message.',
    var: 'Message with {X}.',
    plural: 'You have {N, plural, =0{no messages} one{1 message} other{# messages}}.',
    select: '{GENDER, select, male{He has} female{She has} other{They have}} sent you a message.',
    ordinal: 'The {N, selectordinal, one{1st} two{2nd} few{3rd} other{#th}} message.' };

var mfunc = mf.compile(messages);
```

'mf.compile(messages)' throws an TypeError exception:

```
TypeError: Object #<Object> has no method 'charAt'
    at peg$parsewhitespace (/Users/otbe/node_modules/messageformat/messageformat.js:1292:32)
    at peg$parse_ (/Users/otbe/node_modules/messageformat/messageformat.js:1270:14)
    at peg$parsestring (/Users/otbe/node_modules/messageformat/messageformat.js:963:14)
    at peg$parsemessageFormatPattern (/Users/otbe/node_modules/messageformat/messageformat.js:453:14)
    at peg$parsestart (/Users/otbe/node_modules/messageformat/messageformat.js:439:14)
    at Object.parse (/Users/otbe/node_modules/messageformat/messageformat.js:1303:20)
    at MessageFormat.parse (/Users/otbe/node_modules/messageformat/messageformat.js:1324:26)
    at MessageFormat.compile (/Users/otbe/node_modules/messageformat/messageformat.js:1430:41)
    at repl:1:16
    at REPLServer.self.eval (repl.js:110:21)
```

Do you have any advice for me? Tried with node v0.10.36 and v0.12.2.

Best regards,
otbe

**Comment by eemeli** [comment]
Are you perhaps trying to use `compile()` as above with messageformat 0.2.2 or earlier? The API changed a bit between 0.2 and 0.3, so that should work if you install a newer version, which you can with the following:
```
npm install messageformat@prerelease
```

**Comment by otbe** [comment]
messageformat @ prerelease (0.3.0-1) works like a charm. Thank you!
