### ISSUE TITLE
Readme code seems to not work correctly under node 0.10

### ISSUE THREAD

**Issue by gregglind** [SlexAxton/messageformat.js#125]
https://github.com/SlexAxton/messageformat.js#build-time-compilation

Tried from 'node' repl.  

Maybe I am doing it wrong?

```
> var MessageFormat = require('messageformat');
undefined
> var mf = new MessageFormat('en');
undefined
> var messages = {
...     simple: 'A simple message.',
...     var: 'Message with {X}.',
...     plural: 'You have {N, plural, =0{no messages} one{1 message} other{# messages}}.',
...     select: '{GENDER, select, male{He has} female{She has} other{They have}} sent you a message.',
...     ordinal: 'The {N, selectordinal, one{1st} two{2nd} few{3rd} other{#th}} message.' };
undefined
>
undefined
> var mfunc = mf.compile(messages);
TypeError: Object #<Object> has no method 'charAt'
    at peg$parsewhitespace (/Users/glind/junk/sr2/node_modules/messageformat/messageformat.js:1292:32)
    at peg$parse_ (/Users/glind/junk/sr2/node_modules/messageformat/messageformat.js:1270:14)
    at peg$parsestring (/Users/glind/junk/sr2/node_modules/messageformat/messageformat.js:963:14)
    at peg$parsemessageFormatPattern (/Users/glind/junk/sr2/node_modules/messageformat/messageformat.js:453:14)
    at peg$parsestart (/Users/glind/junk/sr2/node_modules/messageformat/messageformat.js:439:14)
    at Object.parse (/Users/glind/junk/sr2/node_modules/messageformat/messageformat.js:1303:20)
    at MessageFormat.parse (/Users/glind/junk/sr2/node_modules/messageformat/messageformat.js:1324:26)
    at MessageFormat.compile (/Users/glind/junk/sr2/node_modules/messageformat/messageformat.js:1430:41)
    at repl:1:16
    at REPLServer.self.eval (repl.js:110:21)


```

**Comment by gregglind** [comment]
Upgraded to `node 0.12`, getting new things.

```
> vfunc.toString()
'function (d){return "Message with "+i18n.v(d,"X")+"."}'
> var mfunc = mf.compile(messages);
TypeError: undefined is not a function
    at peg$parsewhitespace (/Users/glind/junk/sr2/node_modules/messageformat/messageformat.js:1292:32)
    at peg$parse_ (/Users/glind/junk/sr2/node_modules/messageformat/messageformat.js:1270:14)
    at peg$parsestring (/Users/glind/junk/sr2/node_modules/messageformat/messageformat.js:963:14)
    at peg$parsemessageFormatPattern (/Users/glind/junk/sr2/node_modules/messageformat/messageformat.js:453:14)
    at peg$parsestart (/Users/glind/junk/sr2/node_modules/messageformat/messageformat.js:439:14)
    at Object.parse (/Users/glind/junk/sr2/node_modules/messageformat/messageformat.js:1303:20)
    at MessageFormat.parse (/Users/glind/junk/sr2/node_modules/messageformat/messageformat.js:1324:26)
    at MessageFormat.compile (/Users/glind/junk/sr2/node_modules/messageformat/messageformat.js:1430:41)
    at repl:1:16
    at REPLServer.defaultEval (repl.js:132:27)
> var mfunc = mf.compile(messages.ordinal);
SyntaxError: Expected "," but "o" found.


```

**Comment by eemeli** [comment]
Closing this due to finally releasing [`0.3.0`](/SlexAxton/messageformat.js/releases/tag/v0.3.0). Also, we have a new website at [messageformat.github.io](https://messageformat.github.io/).
