### ISSUE TITLE
No exceptions for undefined 

### ISSUE THREAD

**Issue by lukasz-madon** [SlexAxton/messageformat.js#139]
Given following string `'{RES, plural, =0{no results} one{1 result} other{# results} }'` MessageFormat will throw an exception. Is it possible to pick `# results` in this case?

**Comment by eemeli** [comment]
What version are you using? On 0.3.1 I see this:

```js
> mf = new MesageFormat('en')
> mf.compile('{RES, plural, =0{no results} one{1 result} other{# results} }')({RES:0})
'no results'
> mf.compile('{RES, plural, =0{no results} one{1 result} other{# results} }')({RES:1})
'1 result'
> mf.compile('{RES, plural, =0{no results} one{1 result} other{# results} }')({RES:2})
'2 results'
```

**Comment by lukasz-madon** [comment]
```
> mf.compile('{RES, plural, =0{no results} one{1 result} other{# results} }')({RES:0})
'no results'
> mf.compile('{RES, plural, =0{no results} one{1 result} other{# results} }')({RES:undefined})
Error: 'undefined' isn't a number.
    at Runtime.number (/Users/lukas/Documents/hubot-test/node_modules/messageformat/lib/messageformat.js:242:29)
    at Object.plural.other (eval at <anonymous> (/Users/lukas/Documents/hubot-test/node_modules/messageformat/lib/messageformat.js:519:13), <anonymous>:3:169)
    at Runtime.plural (/Users/lukas/Documents/hubot-test/node_modules/messageformat/lib/messageformat.js:258:38)
    at eval (eval at <anonymous> (/Users/lukas/Documents/hubot-test/node_modules/messageformat/lib/messageformat.js:519:13), <anonymous>:3:29)
    at repl:1:76
    at REPLServer.defaultEval (repl.js:248:27)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:412:12)
    at emitOne (events.js:82:20)
>

mf.compile('{RES, plural, =0{no results} one{1 result} other{# results} }')({})
Error: 'undefined' isn't a number.
    at Runtime.number (/Users/lukas/Documents/hubot-test/node_modules/messageformat/lib/messageformat.js:242:29)
    at Object.plural.other (eval at <anonymous> (/Users/lukas/Documents/hubot-test/node_modules/messageformat/lib/messageformat.js:519:13), <anonymous>:3:169)
    at Runtime.plural (/Users/lukas/Documents/hubot-test/node_modules/messageformat/lib/messageformat.js:258:38)
    at eval (eval at <anonymous> (/Users/lukas/Documents/hubot-test/node_modules/messageformat/lib/messageformat.js:519:13), <anonymous>:3:29)
    at repl:1:76
    at REPLServer.defaultEval (repl.js:248:27)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:412:12)
    at emitOne (events.js:82:20)
```

**Comment by eemeli** [comment]
I'm not really sure what you're presenting as the problem here, or what the solution might be. Your errors are getting thrown by the inclusion of `#` in your `other` case, which requires numerical input. To work around this, try one of the following approaches?

```js
> mf.compile('{RES, plural, =0{no results} one{1 result} other{{RES} results} }')({})
'undefined results'
> mf.compile('{RES, plural, =0{no results} one{1 result} undefined{42} other{# results} }')({})
'42'
```

**Comment by lukasz-madon** [comment]
Yes! That what I was looking for.
